/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframes;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kroctus
 */
public class Acertijos extends javax.swing.JFrame {

    /**
     * Creates new form Acertijos
     */
    /*Cuenta los corazones del jugador si llegan a 0 mueres*/
    private int corazones = 3;

    public Acertijos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siguienteFase = new javax.swing.JButton();
        subirNivel = new javax.swing.JLabel();
        libroDeLosSecretos = new javax.swing.JButton();
        muerte = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        reintentar = new javax.swing.JButton();
        opcionBuena5 = new javax.swing.JButton();
        opcionMala10 = new javax.swing.JButton();
        opcionMala9 = new javax.swing.JButton();
        opcionMala8 = new javax.swing.JButton();
        opcionBuena4 = new javax.swing.JButton();
        opcionMala7 = new javax.swing.JButton();
        opcionMala6 = new javax.swing.JButton();
        opcionMala5 = new javax.swing.JButton();
        opcionBuena3 = new javax.swing.JButton();
        opcionBuena2 = new javax.swing.JButton();
        opcionMala4 = new javax.swing.JButton();
        opcionMala3 = new javax.swing.JButton();
        opcionBuena1 = new javax.swing.JButton();
        opcionMala2 = new javax.swing.JButton();
        opcionMala = new javax.swing.JButton();
        corazonesImg = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ashes of the forgotten World");
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        siguienteFase.setVisible(false);
        siguienteFase.setBackground(new java.awt.Color(204, 0, 204));
        siguienteFase.setForeground(new java.awt.Color(204, 0, 204));
        siguienteFase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/siguientePe.png"))); // NOI18N
        siguienteFase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguienteFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteFaseActionPerformed(evt);
            }
        });
        getContentPane().add(siguienteFase);
        siguienteFase.setBounds(1730, 890, 120, 70);

        subirNivel.setVisible(false);
        subirNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/subisteDeNivel4.png"))); // NOI18N
        getContentPane().add(subirNivel);
        subirNivel.setBounds(0, 0, 1920, 1080);

        libroDeLosSecretos.setVisible(false);
        libroDeLosSecretos.setText("jButton1");
        libroDeLosSecretos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libroDeLosSecretosActionPerformed(evt);
            }
        });
        getContentPane().add(libroDeLosSecretos);
        libroDeLosSecretos.setBounds(1430, 890, 100, 90);

        muerte.setVisible(false);
        muerte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/estasMuerto.png"))); // NOI18N
        getContentPane().add(muerte);
        muerte.setBounds(0, 0, 1920, 1080);

        salir.setVisible(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(670, 130, 580, 150);

        reintentar.setVisible(false);
        reintentar.setText("jButton1");
        reintentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reintentarActionPerformed(evt);
            }
        });
        getContentPane().add(reintentar);
        reintentar.setBounds(670, 370, 580, 150);

        opcionBuena5.setVisible(false);
        opcionBuena5.setBackground(new java.awt.Color(102, 255, 51));
        opcionBuena5.setForeground(new java.awt.Color(0, 255, 204));
        opcionBuena5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionBuena5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionBuena5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBuena5ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionBuena5);
        opcionBuena5.setBounds(770, 420, 260, 340);

        opcionMala10.setVisible(false);
        opcionMala10.setBackground(new java.awt.Color(102, 255, 51));
        opcionMala10.setForeground(new java.awt.Color(0, 255, 204));
        opcionMala10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionMala10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionMala10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMala10ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionMala10);
        opcionMala10.setBounds(1260, 420, 260, 340);

        opcionMala9.setVisible(false);
        opcionMala9.setBackground(new java.awt.Color(102, 255, 51));
        opcionMala9.setForeground(new java.awt.Color(0, 255, 204));
        opcionMala9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionMala9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionMala9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMala9ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionMala9);
        opcionMala9.setBounds(240, 420, 260, 340);

        opcionMala8.setVisible(false);
        opcionMala8.setBackground(new java.awt.Color(102, 255, 51));
        opcionMala8.setForeground(new java.awt.Color(0, 255, 204));
        opcionMala8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionMala8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionMala8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMala8ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionMala8);
        opcionMala8.setBounds(1260, 420, 260, 340);

        opcionBuena4.setVisible(false);
        opcionBuena4.setBackground(new java.awt.Color(102, 255, 51));
        opcionBuena4.setForeground(new java.awt.Color(0, 255, 204));
        opcionBuena4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionBuena4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionBuena4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBuena4ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionBuena4);
        opcionBuena4.setBounds(770, 420, 260, 340);

        opcionMala7.setVisible(false);
        opcionMala7.setBackground(new java.awt.Color(102, 255, 51));
        opcionMala7.setForeground(new java.awt.Color(0, 255, 204));
        opcionMala7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionMala7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionMala7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMala7ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionMala7);
        opcionMala7.setBounds(240, 420, 260, 340);

        opcionMala6.setVisible(false);
        opcionMala6.setBackground(new java.awt.Color(102, 255, 51));
        opcionMala6.setForeground(new java.awt.Color(0, 255, 204));
        opcionMala6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionMala6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionMala6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMala6ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionMala6);
        opcionMala6.setBounds(1260, 420, 260, 340);

        opcionMala5.setVisible(false);
        opcionMala5.setBackground(new java.awt.Color(102, 255, 51));
        opcionMala5.setForeground(new java.awt.Color(0, 255, 204));
        opcionMala5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionMala5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionMala5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMala5ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionMala5);
        opcionMala5.setBounds(770, 420, 260, 340);

        opcionBuena3.setVisible(false);
        opcionBuena3.setBackground(new java.awt.Color(102, 255, 51));
        opcionBuena3.setForeground(new java.awt.Color(0, 255, 204));
        opcionBuena3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionBuena3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionBuena3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBuena3ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionBuena3);
        opcionBuena3.setBounds(240, 420, 260, 340);

        opcionBuena2.setVisible(false);
        opcionBuena2.setBackground(new java.awt.Color(102, 255, 51));
        opcionBuena2.setForeground(new java.awt.Color(0, 255, 204));
        opcionBuena2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionBuena2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionBuena2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBuena2ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionBuena2);
        opcionBuena2.setBounds(240, 420, 260, 340);

        opcionMala4.setVisible(false);
        opcionMala4.setBackground(new java.awt.Color(102, 255, 51));
        opcionMala4.setForeground(new java.awt.Color(0, 255, 204));
        opcionMala4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionMala4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionMala4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMala4ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionMala4);
        opcionMala4.setBounds(1260, 420, 260, 340);

        opcionMala3.setVisible(false);
        opcionMala3.setBackground(new java.awt.Color(102, 255, 51));
        opcionMala3.setForeground(new java.awt.Color(0, 255, 204));
        opcionMala3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionMala3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionMala3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMala3ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionMala3);
        opcionMala3.setBounds(770, 420, 260, 340);

        opcionBuena1.setBackground(new java.awt.Color(102, 255, 51));
        opcionBuena1.setForeground(new java.awt.Color(0, 255, 204));
        opcionBuena1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionBuena1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionBuena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBuena1ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionBuena1);
        opcionBuena1.setBounds(590, 420, 260, 340);

        opcionMala2.setBackground(new java.awt.Color(102, 255, 51));
        opcionMala2.setForeground(new java.awt.Color(0, 255, 204));
        opcionMala2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionMala2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionMala2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMala2ActionPerformed(evt);
            }
        });
        getContentPane().add(opcionMala2);
        opcionMala2.setBounds(1080, 420, 260, 340);

        opcionMala.setBackground(new java.awt.Color(102, 255, 51));
        opcionMala.setForeground(new java.awt.Color(0, 255, 204));
        opcionMala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/interrogacionRedu.png"))); // NOI18N
        opcionMala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionMala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMalaActionPerformed(evt);
            }
        });
        getContentPane().add(opcionMala);
        opcionMala.setBounds(160, 420, 260, 340);

        corazonesImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/tresCorazones.png"))); // NOI18N
        getContentPane().add(corazonesImg);
        corazonesImg.setBounds(1610, 10, 300, 100);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/acertijo1.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(10, -20, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Método para cambiar la cantidad de corazones*/
    public void cambiarCorazones() {
        Icon img;

        switch (corazones) {

            case 3:
                break;

            case 2:
                img = new ImageIcon(getClass().getResource("../imagenes/imagenes/dosCorazones.png"));
                corazonesImg.setIcon(img);
                break;
            case 1:
                img = new ImageIcon(getClass().getResource("../imagenes/imagenes/unCorazones.png"));
                corazonesImg.setIcon(img);
                break;

            case 0:
                muerte.setVisible(true);
                reintentar.setVisible(true);
                salir.setVisible(true);
                break;

            default:
                throw new AssertionError();
        }
    }

    /*Méotodo para comprobar si has ganado o no*/
    public void resultados() {
        if (corazones == 0) {
            muerte.setVisible(true);
            reintentar.setVisible(true);
            salir.setVisible(true);
        } else {
            subirNivel.setVisible(true);
            libroDeLosSecretos.setVisible(true);
        }
    }

    private void opcionMalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMalaActionPerformed
        /*Restamos un corazón*/
        corazones--;

        cambiarCorazones();

        Icon img2;

        /*Ocultamos botones*/
        opcionMala.setVisible(false);
        opcionMala2.setVisible(false);
        opcionBuena1.setVisible(false);

        /*Mostramos los nuevos botones*/
        opcionMala3.setVisible(true);
        opcionMala4.setVisible(true);
        opcionBuena2.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo2.png"));
        fondo.setIcon(img2);

    }//GEN-LAST:event_opcionMalaActionPerformed

    private void opcionMala2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMala2ActionPerformed
        /*Restamos un corazón*/
        corazones--;
        cambiarCorazones();
        Icon img2;


        /*Ocultamos botones*/
        opcionMala.setVisible(false);
        opcionMala2.setVisible(false);
        opcionBuena1.setVisible(false);

        /*Mostramos los nuevos botones*/
        opcionMala3.setVisible(true);
        opcionMala4.setVisible(true);
        opcionBuena2.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo2.png"));
        fondo.setIcon(img2);
    }//GEN-LAST:event_opcionMala2ActionPerformed

    private void opcionBuena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBuena1ActionPerformed

        Icon img2;

        /*Ocultamos botones*/
        opcionMala.setVisible(false);
        opcionMala2.setVisible(false);
        opcionBuena1.setVisible(false);

        /*Mostramos los nuevos botones*/
        opcionMala3.setVisible(true);
        opcionMala4.setVisible(true);
        opcionBuena2.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo2.png"));
        fondo.setIcon(img2);
    }//GEN-LAST:event_opcionBuena1ActionPerformed

    private void opcionMala3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMala3ActionPerformed
        /*Restamos un corazón*/
        corazones--;

        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala3.setVisible(false);
        opcionMala4.setVisible(false);
        opcionBuena2.setVisible(false);

        /*Mostramos los botones nuevos*/
        opcionMala5.setVisible(true);
        opcionMala6.setVisible(true);
        opcionBuena3.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo3.png"));
        fondo.setIcon(img2);
    }//GEN-LAST:event_opcionMala3ActionPerformed

    private void opcionMala4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMala4ActionPerformed
        /*Restamos un corazón*/
        corazones--;

        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala3.setVisible(false);
        opcionMala4.setVisible(false);
        opcionBuena2.setVisible(false);

        /*Mostramos los botones nuevos*/
        opcionMala5.setVisible(true);
        opcionMala6.setVisible(true);
        opcionBuena3.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo3.png"));
        fondo.setIcon(img2);
    }//GEN-LAST:event_opcionMala4ActionPerformed

    private void opcionBuena2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBuena2ActionPerformed

        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala3.setVisible(false);
        opcionMala4.setVisible(false);
        opcionBuena2.setVisible(false);

        /*Mostramos los botones nuevos*/
        opcionMala5.setVisible(true);
        opcionMala6.setVisible(true);
        opcionBuena3.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo3.png"));
        fondo.setIcon(img2);

    }//GEN-LAST:event_opcionBuena2ActionPerformed

    private void opcionBuena3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBuena3ActionPerformed
        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala5.setVisible(false);
        opcionMala6.setVisible(false);
        opcionBuena3.setVisible(false);

        /*Mostramos los botones nuevos*/
        opcionMala7.setVisible(true);
        opcionMala8.setVisible(true);
        opcionBuena4.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo4.png"));
        fondo.setIcon(img2);
    }//GEN-LAST:event_opcionBuena3ActionPerformed

    private void opcionMala5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMala5ActionPerformed
        /*Restamos un corazón*/
        corazones--;

        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala5.setVisible(false);
        opcionMala6.setVisible(false);
        opcionBuena3.setVisible(false);

        /*Mostramos los botones nuevos*/
        opcionMala7.setVisible(true);
        opcionMala8.setVisible(true);
        opcionBuena4.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo4.png"));
        fondo.setIcon(img2);
    }//GEN-LAST:event_opcionMala5ActionPerformed

    private void opcionMala6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMala6ActionPerformed
        /*Restamos un corazón*/
        corazones--;

        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala5.setVisible(false);
        opcionMala6.setVisible(false);
        opcionBuena3.setVisible(false);

//        /*Mostramos los botones nuevos*/
        opcionMala7.setVisible(true);
        opcionMala8.setVisible(true);
        opcionBuena4.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo4.png"));
        fondo.setIcon(img2);
    }//GEN-LAST:event_opcionMala6ActionPerformed

    private void opcionMala7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMala7ActionPerformed
        /*Restamos un corazón*/
        corazones--;

        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala7.setVisible(false);
        opcionMala8.setVisible(false);
        opcionBuena4.setVisible(false);

        /*Mostramos los botones nuevos*/
        opcionMala9.setVisible(true);
        opcionMala10.setVisible(true);
        opcionBuena5.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo5.png"));
        fondo.setIcon(img2);
    }//GEN-LAST:event_opcionMala7ActionPerformed

    private void opcionBuena4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBuena4ActionPerformed
        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala7.setVisible(false);
        opcionMala8.setVisible(false);
        opcionBuena4.setVisible(false);

        /*Mostramos los botones nuevos*/
        opcionMala9.setVisible(true);
        opcionMala10.setVisible(true);
        opcionBuena5.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo5.png"));
        fondo.setIcon(img2);
    }//GEN-LAST:event_opcionBuena4ActionPerformed

    private void opcionMala8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMala8ActionPerformed
        /*Restamos un corazón*/
        corazones--;

        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala7.setVisible(false);
        opcionMala8.setVisible(false);
        opcionBuena4.setVisible(false);

        /*Mostramos los botones nuevos*/
        opcionMala9.setVisible(true);
        opcionMala10.setVisible(true);
        opcionBuena5.setVisible(true);

        /*Cambiamos al siguiente acertijo*/
        img2 = new ImageIcon(getClass().getResource("../imagenes/imagenes/acertijo5.png"));
        fondo.setIcon(img2);
    }//GEN-LAST:event_opcionMala8ActionPerformed

    private void opcionMala9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMala9ActionPerformed
        /*Restamos un corazón*/
        corazones--;

        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala7.setVisible(false);
        opcionMala8.setVisible(false);
        opcionBuena4.setVisible(false);

        /*Mostramos los botones nuevos*/
        opcionMala9.setVisible(true);
        opcionMala10.setVisible(true);
        opcionBuena5.setVisible(true);

        /*Miramos si ha ganado o perdido*/
        resultados();
    }//GEN-LAST:event_opcionMala9ActionPerformed

    private void opcionMala10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMala10ActionPerformed
        /*Restamos un corazón*/
        corazones--;

        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala7.setVisible(false);
        opcionMala8.setVisible(false);
        opcionBuena4.setVisible(false);

        /*Mostramos los botones nuevos*/
        opcionMala9.setVisible(true);
        opcionMala10.setVisible(true);
        opcionBuena5.setVisible(true);

        /*Miramos si ha ganado o perdido*/
        resultados();
    }//GEN-LAST:event_opcionMala10ActionPerformed

    private void opcionBuena5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBuena5ActionPerformed
        Icon img2;

        cambiarCorazones();
        /*Ocultamos botones*/
        opcionMala7.setVisible(false);
        opcionMala8.setVisible(false);
        opcionBuena4.setVisible(false);

        /*Mostramos los botones nuevos*/
        opcionMala9.setVisible(true);
        opcionMala10.setVisible(true);
        opcionBuena5.setVisible(true);

        /*Miramos si ha ganado o perdido*/
        resultados();
    }//GEN-LAST:event_opcionBuena5ActionPerformed

    private void reintentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reintentarActionPerformed
        new Acertijos().setVisible(true);
        dispose();
    }//GEN-LAST:event_reintentarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void siguienteFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteFaseActionPerformed

        new Charla2().setVisible(true);
        dispose();
    }//GEN-LAST:event_siguienteFaseActionPerformed

    private void libroDeLosSecretosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libroDeLosSecretosActionPerformed
        new LibroDeLosSecretos2().setVisible(true);
    }//GEN-LAST:event_libroDeLosSecretosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acertijos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acertijos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acertijos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acertijos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acertijos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel corazonesImg;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton libroDeLosSecretos;
    private javax.swing.JLabel muerte;
    private javax.swing.JButton opcionBuena1;
    private javax.swing.JButton opcionBuena2;
    private javax.swing.JButton opcionBuena3;
    private javax.swing.JButton opcionBuena4;
    private javax.swing.JButton opcionBuena5;
    private javax.swing.JButton opcionMala;
    private javax.swing.JButton opcionMala10;
    private javax.swing.JButton opcionMala2;
    private javax.swing.JButton opcionMala3;
    private javax.swing.JButton opcionMala4;
    private javax.swing.JButton opcionMala5;
    private javax.swing.JButton opcionMala6;
    private javax.swing.JButton opcionMala7;
    private javax.swing.JButton opcionMala8;
    private javax.swing.JButton opcionMala9;
    private javax.swing.JButton reintentar;
    private javax.swing.JButton salir;
    private javax.swing.JButton siguienteFase;
    private javax.swing.JLabel subirNivel;
    // End of variables declaration//GEN-END:variables
}
