/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframes;

/**
 *
 * @author kroctus
 */
public class EleccionHistoria extends javax.swing.JFrame {

    /**
     * Creates new form EleccionHistoria
     */
    public EleccionHistoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonHistoriaPrincipal = new javax.swing.JButton();
        botonHistoriasAlternativas = new javax.swing.JButton();
        labelHistoriaPrincipal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelEligeTuHistoria = new javax.swing.JLabel();
        imagen_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1921, 1201));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(botonHistoriaPrincipal);
        botonHistoriaPrincipal.setBounds(480, 370, 250, 270);

        botonHistoriasAlternativas.setText("jButton1");
        getContentPane().add(botonHistoriasAlternativas);
        botonHistoriasAlternativas.setBounds(1110, 370, 250, 270);

        labelHistoriaPrincipal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        labelHistoriaPrincipal.setText("Historia principal");
        getContentPane().add(labelHistoriaPrincipal);
        labelHistoriaPrincipal.setBounds(420, 660, 540, 60);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel1.setText("Historias alternativas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1030, 670, 457, 64);

        labelEligeTuHistoria.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 70)); // NOI18N
        labelEligeTuHistoria.setText("Elige tu historia:");
        getContentPane().add(labelEligeTuHistoria);
        labelEligeTuHistoria.setBounds(60, 80, 810, 90);

        imagen_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/ARMAS.png"))); // NOI18N
        imagen_fondo.setText("jLabel1");
        getContentPane().add(imagen_fondo);
        imagen_fondo.setBounds(0, 0, 1910, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EleccionHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EleccionHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EleccionHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EleccionHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EleccionHistoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonHistoriaPrincipal;
    private javax.swing.JButton botonHistoriasAlternativas;
    private javax.swing.JLabel imagen_fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelEligeTuHistoria;
    private javax.swing.JLabel labelHistoriaPrincipal;
    // End of variables declaration//GEN-END:variables
}
