/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframes;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author kroctus
 */
public class LibroDeLosSecretos2 extends javax.swing.JFrame {

    /**
     * Creates new form LibroDeLosSecretos
     */
    public LibroDeLosSecretos2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JLabel();
        trishButtom = new javax.swing.JButton();
        fugggieBoton = new javax.swing.JButton();
        golemBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ashes of the forgotten world");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(null);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/elLibroDeLosSecretos2.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 1920, 1080);

        trishButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trishButtomActionPerformed(evt);
            }
        });
        getContentPane().add(trishButtom);
        trishButtom.setBounds(460, 250, 140, 170);

        fugggieBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fugggieBotonActionPerformed(evt);
            }
        });
        getContentPane().add(fugggieBoton);
        fugggieBoton.setBounds(90, 240, 140, 190);

        golemBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                golemBotonActionPerformed(evt);
            }
        });
        getContentPane().add(golemBoton);
        golemBoton.setBounds(270, 240, 140, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fugggieBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fugggieBotonActionPerformed
        Icon img;

        img = new ImageIcon(getClass().getResource("../imagenes/imagenes/elLibroDeLosSecretosFuggie2.png"));
        fondo.setIcon(img);

    }//GEN-LAST:event_fugggieBotonActionPerformed

    private void golemBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_golemBotonActionPerformed
        Icon img;

        img = new ImageIcon(getClass().getResource("../imagenes/imagenes/elLibroDeLosSecretosGolem2.png"));
        fondo.setIcon(img);
    }//GEN-LAST:event_golemBotonActionPerformed

    private void trishButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trishButtomActionPerformed
        Icon img;

        img = new ImageIcon(getClass().getResource("../imagenes/imagenes/elLibroDeLosSecretosTrish.png"));
        fondo.setIcon(img);
    }//GEN-LAST:event_trishButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibroDeLosSecretos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibroDeLosSecretos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibroDeLosSecretos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibroDeLosSecretos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibroDeLosSecretos2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton fugggieBoton;
    private javax.swing.JButton golemBoton;
    private javax.swing.JButton trishButtom;
    // End of variables declaration//GEN-END:variables
}
