/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframes;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author kroctus
 */
public class Tutorial2 extends javax.swing.JFrame {

    /**
     * Creates new form Tutorial2
     */
    /**/
    private int contadorSiguiente;

    public Tutorial2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siguiente = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ashes of the forgotten World");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        siguiente.setBackground(new java.awt.Color(204, 255, 204));
        siguiente.setForeground(new java.awt.Color(204, 255, 204));
        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/siguientePe.png"))); // NOI18N
        siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente);
        siguiente.setBounds(1710, 920, 160, 80);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/tuto1.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        Icon img;

        switch (contadorSiguiente) {
            case 0:

                img = new ImageIcon(getClass().getResource("/imagenes/imagenes/tuto2.png"));
                fondo.setIcon(img);
                contadorSiguiente++;
                break;
            case 1:
                img = new ImageIcon(getClass().getResource("/imagenes/imagenes/tuto3.png"));
                fondo.setIcon(img);
                contadorSiguiente++;
                break;
            case 2:
                img = new ImageIcon(getClass().getResource("/imagenes/imagenes/tuto4.png"));
                fondo.setIcon(img);
                contadorSiguiente++;
                break;
            case 3:
                img = new ImageIcon(getClass().getResource("/imagenes/imagenes/tuto5.png"));
                fondo.setIcon(img);
                contadorSiguiente++;
                break;
            case 4:
                img = new ImageIcon(getClass().getResource("/imagenes/imagenes/tuto6.png"));
                fondo.setIcon(img);
                contadorSiguiente++;
                break;

            case 5:
                img = new ImageIcon(getClass().getResource("/imagenes/imagenes/tuto7.png"));
                fondo.setIcon(img);
                contadorSiguiente++;
                break;

            case 6:
                img = new ImageIcon(getClass().getResource("/imagenes/imagenes/tuto8.png"));
                fondo.setIcon(img);
                contadorSiguiente++;
                break;

            case 7:
                 img= new ImageIcon(getClass().getResource("/imagenes/imagenes/tuto10.png"));
                fondo.setIcon(img);
                contadorSiguiente++;
                break;

            case 8:
                 img= new ImageIcon(getClass().getResource("/imagenes/imagenes/tuto11.png"));
                fondo.setIcon(img);
                contadorSiguiente++;
                break;

            case 9:
               
                new CombateTutorial().setVisible(true);
                dispose();
                break;

           

        }


    }//GEN-LAST:event_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorial2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
