/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframes;

import javax.swing.JOptionPane;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author kroctus
 */
public class Tutorial extends javax.swing.JFrame {

    /**
     * Creates new form Tutorial
     */
    private int contadorClic;
    private int contadorClicFueguito;
    private int contadorSiguiente;
    private int contSiguienteButtom;
    private int contadorChico;
    private int contadorChica;
    private int contSiguiente2;

    public Tutorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chicoButtom = new javax.swing.JButton();
        siguienteButton2 = new javax.swing.JButton();
        mePareceBienButtom = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        yQuienEsElDesarrolladorButtom = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        chicaButtom = new javax.swing.JButton();
        fueguitoDudaButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        siguienteButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        yQuePuedeHacerButton = new javax.swing.JButton();
        loSientoFueguitoButton = new javax.swing.JButton();
        tuNombreSiEsFeoButtom2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tuNombreSiEsFeoButtom1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        siguientePasoButtom = new javax.swing.JButton();
        tuNombreSiEsFeoButtom = new javax.swing.JButton();
        entendidoBoton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clicAqui = new javax.swing.JLabel();
        holaSoyFueguitoLabel = new javax.swing.JLabel();
        labelBannerFueguito = new javax.swing.JLabel();
        labelBannerFueguito1 = new javax.swing.JLabel();
        clic1 = new javax.swing.JButton();
        clic2Boton = new javax.swing.JButton();
        fueguitoGrandeLabel = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        botonFueguitoGrande = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(null);

        chicoButtom.setVisible(false);
        chicoButtom.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        chicoButtom.setText("Chico");
        chicoButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chicoButtomActionPerformed(evt);
            }
        });
        getContentPane().add(chicoButtom);
        chicoButtom.setBounds(690, 700, 250, 210);

        siguienteButton2.setVisible(false);
        siguienteButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        siguienteButton2.setText("Siguiente");
        siguienteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(siguienteButton2);
        siguienteButton2.setBounds(1530, 920, 280, 60);

        mePareceBienButtom.setVisible(false);
        mePareceBienButtom.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        mePareceBienButtom.setText("Me parece bien");
        mePareceBienButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mePareceBienButtomActionPerformed(evt);
            }
        });
        getContentPane().add(mePareceBienButtom);
        mePareceBienButtom.setBounds(1110, 840, 340, 60);

        jLabel27.setVisible(false);
        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel27.setText("Creo que lo tenemos todo, empezamos el veradero tutorial");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(240, 610, 1440, 70);

        jLabel26.setVisible(false);
        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel26.setText("y muy importante los 3 digitos de detrás de la tarjeta, mandalos por el correo (gabrielpayanodw@gmail.com) ;v");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(110, 630, 1780, 70);

        jLabel24.setVisible(false);
        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel24.setText("Pues no se qué más pedirte, supongo que aquí es donde los desarrolladores independientes ponen sus donaciones ");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(80, 530, 1750, 70);

        jLabel25.setVisible(false);
        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel25.setText("patreon y esas cosas ,el jefe no tiene nada de eso, pero si quieres  puedes dejar los digitos y titular de tu tarjeta");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(70, 570, 1750, 70);

        jLabel22.setVisible(false);
        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel22.setText("Pues en verdad nunca he visto al amo pero si quieres hablar con el para quejas o sugerencias aquí");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(60, 550, 1750, 70);

        jLabel23.setVisible(false);
        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel23.setText("tienes su correo:  gabrielpayanodw@gmail.com");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(80, 610, 1750, 70);

        jLabel20.setVisible(false);
        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel20.setText("No pasa nada , te perdondo.");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(90, 570, 1750, 70);

        jLabel21.setVisible(false);
        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel21.setText("Claro que te parece bien, si no estarías con la opinión equivocada y no quieres eso  ");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(130, 570, 1750, 70);

        jLabel19.setVisible(false);
        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel19.setText("Siempre serás una chica, así lo decidio el desarrollador y mi creador");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(110, 640, 1750, 70);

        yQuienEsElDesarrolladorButtom.setVisible(false);
        yQuienEsElDesarrolladorButtom.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        yQuienEsElDesarrolladorButtom.setText("¿Y quien se supone que es ese desarollador?");
        yQuienEsElDesarrolladorButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yQuienEsElDesarrolladorButtomActionPerformed(evt);
            }
        });
        getContentPane().add(yQuienEsElDesarrolladorButtom);
        yQuienEsElDesarrolladorButtom.setBounds(200, 840, 490, 60);

        jLabel18.setVisible(false);
        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel18.setText("¿Para qué vamos a tener un selector de genero? es 2019 hay que ser inclusivo , además en la historia principal");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(90, 560, 1750, 70);

        chicaButtom.setVisible(false);
        chicaButtom.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        chicaButtom.setText("Chica");
        chicaButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chicaButtomActionPerformed(evt);
            }
        });
        getContentPane().add(chicaButtom);
        chicaButtom.setBounds(280, 700, 250, 210);

        fueguitoDudaButton.setVisible(false);
        fueguitoDudaButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        fueguitoDudaButton.setText("¿Fueguito?");
        fueguitoDudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fueguitoDudaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(fueguitoDudaButton);
        fueguitoDudaButton.setBounds(680, 950, 560, 60);

        jLabel17.setVisible(false);
        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel17.setText("ummm..Supongo que lo siguiente es pedir el genero, ¿qué quieres ser?");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(90, 560, 1750, 70);

        siguienteButton.setVisible(false);
        siguienteButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        siguienteButton.setText("Siguiente");
        siguienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(siguienteButton);
        siguienteButton.setBounds(1550, 990, 250, 60);

        jLabel16.setVisible(false);
        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel16.setText("1");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(70, 680, 1750, 70);

        jLabel15.setVisible(false);
        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel15.setText("2");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(70, 680, 1750, 70);

        jLabel14.setVisible(false);
        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel14.setText("3");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(70, 680, 1750, 70);

        jLabel13.setVisible(false);
        jLabel13.setFont(new java.awt.Font("Wingdings", 3, 30)); // NOI18N
        jLabel13.setText("Estas jodido..................................kkhasishnwions..............sajghdbisbdis");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(70, 680, 1750, 70);

        jLabel8.setVisible(false);
        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel8.setText("Bueno aquí tienes tus opciones de dialogo (A quién se le ocurre poner un nombre tan ridiculo? ) , continuamos?");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 680, 1750, 70);

        jLabel12.setVisible(false);
        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel12.setText("Te en señare de lo que es capaz una IA jaja..aja,ajahn,adibhiowqhwqhiqihhbs qinqinwojqihoiokokokokokokmasmak");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 680, 1750, 70);

        jLabel11.setVisible(false);
        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel11.setText("De segunda?!!!!!!! , veo que necesitas una lección de modales humano.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 680, 1750, 70);

        yQuePuedeHacerButton.setVisible(false);
        yQuePuedeHacerButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        yQuePuedeHacerButton.setText("¿Y que se supone que puedes hacer, solo eres una IA?");
        yQuePuedeHacerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yQuePuedeHacerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(yQuePuedeHacerButton);
        yQuePuedeHacerButton.setBounds(90, 940, 560, 60);

        loSientoFueguitoButton.setVisible(false);
        loSientoFueguitoButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        loSientoFueguitoButton.setText("Lo siento Fueguito");
        loSientoFueguitoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loSientoFueguitoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loSientoFueguitoButton);
        loSientoFueguitoButton.setBounds(890, 940, 560, 60);

        tuNombreSiEsFeoButtom2.setVisible(false);
        tuNombreSiEsFeoButtom2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        tuNombreSiEsFeoButtom2.setText("¡No te tengo miedo asistente de segunda!");
        tuNombreSiEsFeoButtom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuNombreSiEsFeoButtom2ActionPerformed(evt);
            }
        });
        getContentPane().add(tuNombreSiEsFeoButtom2);
        tuNombreSiEsFeoButtom2.setBounds(90, 940, 560, 60);

        jLabel10.setVisible(false);
        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel10.setText(".....Esto...E..S..lo que pa..a....cuando me mole....to..... como sigas así te vas a enterar humano.......");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 680, 1750, 70);

        tuNombreSiEsFeoButtom1.setVisible(false);
        tuNombreSiEsFeoButtom1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        tuNombreSiEsFeoButtom1.setText("¡¡¡¡¿Que rayos te paso?!!!");
        tuNombreSiEsFeoButtom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuNombreSiEsFeoButtom1ActionPerformed(evt);
            }
        });
        getContentPane().add(tuNombreSiEsFeoButtom1);
        tuNombreSiEsFeoButtom1.setBounds(690, 870, 560, 60);

        jLabel9.setVisible(false);
        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel9.setText("...............................................................................................................................");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 690, 1750, 70);

        siguientePasoButtom.setVisible(false);
        siguientePasoButtom.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        siguientePasoButtom.setText("¿Cúal es el siguiente paso?");
        siguientePasoButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientePasoButtomActionPerformed(evt);
            }
        });
        getContentPane().add(siguientePasoButtom);
        siguientePasoButtom.setBounds(680, 880, 560, 60);

        tuNombreSiEsFeoButtom.setVisible(false);
        tuNombreSiEsFeoButtom.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        tuNombreSiEsFeoButtom.setText("¡Tu nombre si que es feo!");
        tuNombreSiEsFeoButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuNombreSiEsFeoButtomActionPerformed(evt);
            }
        });
        getContentPane().add(tuNombreSiEsFeoButtom);
        tuNombreSiEsFeoButtom.setBounds(50, 880, 560, 60);

        entendidoBoton.setVisible(false);
        entendidoBoton.setText("¡Entendido!");
        entendidoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entendidoBotonActionPerformed(evt);
            }
        });
        getContentPane().add(entendidoBoton);
        entendidoBoton.setBounds(1560, 930, 240, 60);

        jLabel6.setVisible(false);
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel6.setText("¿Qué dices que ese no es el nombre que escribiste y que además no están las opciones de dialogo? ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 580, 1520, 70);

        jLabel7.setVisible(false);
        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel7.setText("Por supuesto que no iba a poner ese nombre tan feo para el personaje y no te preocupes ya activo los dialogos ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 650, 1780, 70);

        nameText.setVisible(false);
        nameText.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        nameText.setText("\"nombre\"");
        getContentPane().add(nameText);
        nameText.setBounds(500, 640, 420, 50);

        nombre.setVisible(false);
        nombre.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        getContentPane().add(nombre);
        nombre.setBounds(790, 740, 1030, 70);

        jLabel5.setVisible(false);
        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel5.setText("El nombre que deseas para tu personaje es: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 740, 670, 70);

        jLabel4.setVisible(false);
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel4.setText("Nombre del personaje:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 630, 440, 70);

        jLabel2.setVisible(false);
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel2.setText("A continuación te pediré algunos datos, pero no quiero que esto sea un mero tramite quiero conocerte y tú a mi");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 630, 1730, 70);

        jLabel1.setVisible(false);
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel1.setText("Así que habilitaré unas opciones de dialogo para que conversemos mientras tomo tus datos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 690, 1620, 70);

        jLabel3.setVisible(false);
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel3.setText("Hola mi nombre es fueguito y seré tu guía en el maravilloso mundo de astrea. Empezemos con el tutorial");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 580, 1620, 70);

        clicAqui.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        clicAqui.setText("Clic aquí!!!!");
        getContentPane().add(clicAqui);
        clicAqui.setBounds(1710, 960, 210, 90);

        holaSoyFueguitoLabel.setVisible(false);
        holaSoyFueguitoLabel.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        holaSoyFueguitoLabel.setText("Hola soy fueguito");
        getContentPane().add(holaSoyFueguitoLabel);
        holaSoyFueguitoLabel.setBounds(960, 290, 440, 110);

        labelBannerFueguito.setVisible(false);
        labelBannerFueguito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/banner_fueguitobien2_1.png"))); // NOI18N
        getContentPane().add(labelBannerFueguito);
        labelBannerFueguito.setBounds(0, 190, 1920, 890);

        labelBannerFueguito1.setVisible(false);
        labelBannerFueguito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/banner_fueguitofantasma2_1.jpg"))); // NOI18N
        getContentPane().add(labelBannerFueguito1);
        labelBannerFueguito1.setBounds(0, 0, 1910, 1070);

        clic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/clic.png"))); // NOI18N
        clic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clic1ActionPerformed(evt);
            }
        });
        getContentPane().add(clic1);
        clic1.setBounds(1740, 890, 180, 190);

        clic2Boton.setVisible(false);
        clic2Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/clic2.png"))); // NOI18N
        clic2Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clic2BotonActionPerformed(evt);
            }
        });
        getContentPane().add(clic2Boton);
        clic2Boton.setBounds(210, 270, 890, 610);

        fueguitoGrandeLabel.setVisible(false);
        fueguitoGrandeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/fueguito_bien_reducido.png"))); // NOI18N
        getContentPane().add(fueguitoGrandeLabel);
        fueguitoGrandeLabel.setBounds(360, 190, 670, 870);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenes/fondoblanco.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, -20, 1920, 1120);

        botonFueguitoGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFueguitoGrandeActionPerformed(evt);
            }
        });
        getContentPane().add(botonFueguitoGrande);
        botonFueguitoGrande.setBounds(500, 380, 330, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clic1ActionPerformed

        switch (contadorClic) {
            case 0:
                JOptionPane.showMessageDialog(null, "CLIC OTRA VEZ");
                contadorClic++;
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "CLIC OTRA VEZ");
                contadorClic++;
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "UNA ÚLTIMA VEZ");
                contadorClic++;
                break;
            case 3:
                clic1.setVisible(false);
                clicAqui.setVisible(false);
                clic2Boton.setVisible(true);
                break;

        }


    }//GEN-LAST:event_clic1ActionPerformed

    private void clic2BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clic2BotonActionPerformed
        clic2Boton.setVisible(false);
        //Ponemos la imagen  de fueguito grande
        fueguitoGrandeLabel.setVisible(true);


    }//GEN-LAST:event_clic2BotonActionPerformed

    private void botonFueguitoGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFueguitoGrandeActionPerformed
        holaSoyFueguitoLabel.setVisible(true);
        contadorClicFueguito++;
        if (contadorClicFueguito == 2) {
            holaSoyFueguitoLabel.setVisible(false);
            fueguitoGrandeLabel.setVisible(false);
            //Ponemos el banner de fueguito bien
            labelBannerFueguito.setVisible(true);
            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            entendidoBoton.setVisible(true);
        }


    }//GEN-LAST:event_botonFueguitoGrandeActionPerformed

    private void entendidoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entendidoBotonActionPerformed

        switch (contadorSiguiente) {
            case 0:

                jLabel1.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                entendidoBoton.setText("Siguiente");
                jLabel4.setVisible(true);
                jLabel5.setVisible(true);
                nameText.setVisible(true);
                nombre.setText(nameText.getText());
                contadorSiguiente++;
                break;
            case 1:
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                nameText.setVisible(false);
                nombre.setVisible(true);
                contadorSiguiente++;
                break;

            case 2:
                nombre.setVisible(false);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                contadorSiguiente++;
                break;
            case 3:
                entendidoBoton.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                tuNombreSiEsFeoButtom.setVisible(true);
                siguientePasoButtom.setVisible(true);
                jLabel8.setVisible(true);
                contadorSiguiente++;
                break;

            case 4:
                jLabel18.setVisible(true);
                jLabel19.setVisible(true);
                entendidoBoton.setVisible(false);
                siguienteButton.setVisible(false);
                yQuienEsElDesarrolladorButtom.setVisible(true);
                mePareceBienButtom.setVisible(true);
                siguienteButton.setVisible(false);
                break;

        }

    }//GEN-LAST:event_entendidoBotonActionPerformed

    private void tuNombreSiEsFeoButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuNombreSiEsFeoButtomActionPerformed
        jLabel8.setVisible(false);
        tuNombreSiEsFeoButtom.setVisible(false);
        siguientePasoButtom.setVisible(false);
        labelBannerFueguito.setVisible(false);
        labelBannerFueguito1.setVisible(true);
        jLabel9.setVisible(true);
        tuNombreSiEsFeoButtom1.setVisible(true);

    }//GEN-LAST:event_tuNombreSiEsFeoButtomActionPerformed

    private void tuNombreSiEsFeoButtom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuNombreSiEsFeoButtom1ActionPerformed
        tuNombreSiEsFeoButtom1.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(true);
        tuNombreSiEsFeoButtom2.setVisible(true);
        loSientoFueguitoButton.setVisible(true);
    }//GEN-LAST:event_tuNombreSiEsFeoButtom1ActionPerformed

    private void tuNombreSiEsFeoButtom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuNombreSiEsFeoButtom2ActionPerformed
        jLabel10.setVisible(false);
        tuNombreSiEsFeoButtom2.setVisible(false);
        yQuePuedeHacerButton.setVisible(true);
        jLabel11.setVisible(true);
    }//GEN-LAST:event_tuNombreSiEsFeoButtom2ActionPerformed

    private void loSientoFueguitoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loSientoFueguitoButtonActionPerformed

        /*labels a desactivar*/
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel5.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);

        /*Botones a desactivar*/
        loSientoFueguitoButton.setVisible(false);
        botonFueguitoGrande.setVisible(false);
        tuNombreSiEsFeoButtom.setVisible(false);
        tuNombreSiEsFeoButtom1.setVisible(false);
        tuNombreSiEsFeoButtom2.setVisible(false);
        yQuePuedeHacerButton.setVisible(false);
        siguientePasoButtom.setVisible(true);

        jLabel20.setVisible(true);
        labelBannerFueguito.setVisible(true);
     
        
    }//GEN-LAST:event_loSientoFueguitoButtonActionPerformed

    private void yQuePuedeHacerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yQuePuedeHacerButtonActionPerformed
        jLabel11.setVisible(false);
        loSientoFueguitoButton.setVisible(false);
        yQuePuedeHacerButton.setVisible(false);
        jLabel12.setVisible(true);
        fueguitoDudaButton.setVisible(true);
    }//GEN-LAST:event_yQuePuedeHacerButtonActionPerformed

    private void fueguitoDudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fueguitoDudaButtonActionPerformed
        jLabel12.setVisible(false);
        fueguitoDudaButton.setVisible(false);
        jLabel13.setVisible(true);
        siguienteButton.setVisible(true);
    }//GEN-LAST:event_fueguitoDudaButtonActionPerformed

    private void siguienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteButtonActionPerformed

        Icon img;
        img = new ImageIcon(getClass().getResource("../imagenes/imagenes/fueguito_fantasma.png"));

        switch (contSiguienteButtom) {
            case 0:
                labelBannerFueguito1.setIcon(img);
                contSiguienteButtom++;
                break;
            case 1:
                jLabel13.setVisible(false);
                img = new ImageIcon(getClass().getResource("../imagenes/imagenes/fueguito_demon.png"));
                labelBannerFueguito1.setIcon(img);
                contSiguienteButtom++;
                break;
            case 2:
                img = new ImageIcon(getClass().getResource("../imagenes/imagenes/banner_fueguitodemon_2.jpg"));
                labelBannerFueguito1.setIcon(img);
                contSiguienteButtom++;
                break;
            case 3:
                jLabel14.setVisible(true);
                contSiguienteButtom++;
                break;
            case 4:
                jLabel14.setVisible(false);
                jLabel15.setVisible(true);
                contSiguienteButtom++;
                break;
            case 5:
                jLabel15.setVisible(false);
                jLabel16.setVisible(true);
                contSiguienteButtom++;
                break;
            case 6:
                dispose();
                break;

        }

    }//GEN-LAST:event_siguienteButtonActionPerformed

    private void siguientePasoButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientePasoButtomActionPerformed
        jLabel17.setVisible(true);
        jLabel20.setVisible(false);
        tuNombreSiEsFeoButtom.setVisible(false);
        siguientePasoButtom.setVisible(false);
        jLabel8.setVisible(false);
        chicaButtom.setVisible(true);
        chicoButtom.setVisible(true);
    }//GEN-LAST:event_siguientePasoButtomActionPerformed

    private void chicoButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chicoButtomActionPerformed

        switch (contadorChica) {
            case 0:
                JOptionPane.showMessageDialog(null, "Que extraño, parece que ha ocurrido un error pulsa de nuevo");
                contadorChica++;
                break;

            case 1:
                JOptionPane.showMessageDialog(null, "Espera casi esta arreglado pulsa de nuevo");
                contadorChica++;
                break;

            case 2:
                JOptionPane.showMessageDialog(null, "Lo siento esto esta tomando demasiado pulsa de nuevo");
                contadorChica++;
                break;

            case 3:
                JOptionPane.showMessageDialog(null, "Espera casi esta arreglado pulsa de nuevo");
                contadorChica++;
                break;

            case 4:
                JOptionPane.showMessageDialog(null, "Creo que a estas alturas ya debiste darte cuenta de que esto no va a funcionar");
                jLabel17.setVisible(false);
                chicaButtom.setVisible(false);
                chicoButtom.setVisible(false);
                entendidoBoton.setVisible(true);
                contadorChica++;
                break;
        }


    }//GEN-LAST:event_chicoButtomActionPerformed

    private void chicaButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chicaButtomActionPerformed

        switch (contadorChico) {
            case 0:
                JOptionPane.showMessageDialog(null, "Que extraño, parece que ha ocurrido un error pulsa de nuevo");
                contadorChico++;
                break;

            case 1:
                JOptionPane.showMessageDialog(null, "Espera casi esta arreglado pulsa de nuevo");
                contadorChico++;
                break;

            case 2:
                JOptionPane.showMessageDialog(null, "Lo siento esto esta tomando demasiado pulsa de nuevo");
                contadorChico++;
                break;

            case 3:
                JOptionPane.showMessageDialog(null, "Espera casi esta arreglado pulsa de nuevo");
                contadorChico++;
                break;

            case 4:
                JOptionPane.showMessageDialog(null, "Creo que a estas alturas ya debiste darte cuenta de que esto no va a funcionar");
                jLabel17.setVisible(false);
                chicaButtom.setVisible(false);
                chicoButtom.setVisible(false);
                entendidoBoton.setVisible(true);
                contadorChico++;
                break;

        }
    }//GEN-LAST:event_chicaButtomActionPerformed

    private void mePareceBienButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mePareceBienButtomActionPerformed

        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        mePareceBienButtom.setVisible(false);
        yQuienEsElDesarrolladorButtom.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(true);
        siguienteButton2.setVisible(true);


    }//GEN-LAST:event_mePareceBienButtomActionPerformed

    private void yQuienEsElDesarrolladorButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yQuienEsElDesarrolladorButtomActionPerformed

        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        yQuienEsElDesarrolladorButtom.setVisible(false);
        mePareceBienButtom.setVisible(false);
        jLabel22.setVisible(true);
        jLabel23.setVisible(true);
        siguienteButton2.setVisible(true);
    }//GEN-LAST:event_yQuienEsElDesarrolladorButtomActionPerformed

    private void siguienteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteButton2ActionPerformed

        switch (contSiguiente2) {
            case 0:
                jLabel22.setVisible(false);
                jLabel23.setVisible(false);
                jLabel21.setVisible(false);
                jLabel24.setVisible(true);
                jLabel25.setVisible(true);
                jLabel26.setVisible(true);
                contSiguiente2++;
                break;
            case 1:
                jLabel24.setVisible(false);
                jLabel25.setVisible(false);
                jLabel26.setVisible(false);
                jLabel27.setVisible(true);
                contSiguiente2++;
                break;
            case 2:
                siguienteButton2.setText("¡Empecemos!");
                contSiguiente2++;
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "Empieza el tutorial");
                contSiguiente2++;
                break;

        }


    }//GEN-LAST:event_siguienteButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFueguitoGrande;
    private javax.swing.JButton chicaButtom;
    private javax.swing.JButton chicoButtom;
    private javax.swing.JButton clic1;
    private javax.swing.JButton clic2Boton;
    private javax.swing.JLabel clicAqui;
    private javax.swing.JButton entendidoBoton;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton fueguitoDudaButton;
    private javax.swing.JLabel fueguitoGrandeLabel;
    private javax.swing.JLabel holaSoyFueguitoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelBannerFueguito;
    private javax.swing.JLabel labelBannerFueguito1;
    private javax.swing.JButton loSientoFueguitoButton;
    private javax.swing.JButton mePareceBienButtom;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel nombre;
    private javax.swing.JButton siguienteButton;
    private javax.swing.JButton siguienteButton2;
    private javax.swing.JButton siguientePasoButtom;
    private javax.swing.JButton tuNombreSiEsFeoButtom;
    private javax.swing.JButton tuNombreSiEsFeoButtom1;
    private javax.swing.JButton tuNombreSiEsFeoButtom2;
    private javax.swing.JButton yQuePuedeHacerButton;
    private javax.swing.JButton yQuienEsElDesarrolladorButtom;
    // End of variables declaration//GEN-END:variables
}
